slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::AztecSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    map_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link
    scan_topic: /scan
    mode: mapping
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
